# Generated by Django 4.0.1 on 2022-01-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('Caring and Sharing Meetings', 'Caring and Sharing Meetings'), ('Committees', 'Committees'), ('FaithNet', 'FaithNet'), ('Family-to-Family', 'Family-to-Family'), ('Fundraising', 'Fundraising'), ('Family Meeting', 'Family Meeting'), ('In Our Own Voice', 'In our Own Voice'), ('Spirituality', 'Support Groups'), ('Peer-to-Peer', 'Peer-to-Peer'), ('Peer Support Group', 'Peer Support Group'), ('Peer Support Group2', 'Peer Support Group2'), ('WALK', 'WALK'), ('Legislative Night', 'Legislative Night'), ('Whole Family Support', 'Whole Family Support')], default='DEF', max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.TextField(blank=True)),
            ],
        ),
    ]
