# Generated by Django 4.0.1 on 2022-01-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Caring and Sharing Meetings', 'Caring and Sharing Meetings'), ('Committees', 'Committees'), ('FaithNet', 'FaithNet'), ('Family-to-Family', 'Family-to-Family'), ('Fundraising', 'Fundraising'), ('In Our Own Voice', 'In our Own Voice'), ('Spirituality', 'Support Groups'), ('Peer-to-Peer', 'Peer-to-Peer'), ('Peer Support Group', 'Peer Support Group'), ('WALK', 'WALK'), ('Legislative Night', 'Legislative Night'), ('Whole Family Support', 'Whole Family Support')], default='DEF', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='people.person')),
            ],
        ),
    ]
